apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
  labels:
    app: tinyapp-pipeline
  name: tinyapp-deploy
spec:
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      env:
      jenkinsfile: |-
        pipeline {
          agent any
          stages {
            stage('Deploy TinyApp') {
              steps {
                script {
                  openshift.withCluster() {
                    openshift.withProject() {
                      openshift.patch("dc/tinyapp", '\'{"spec": {"template": {"spec": {"containers": [{"name": "tinyapp", "image": "quay.io/siamaksade/tinyapp:v2"}]}}}}\'')
                      openshift.selector("dc", "tinyapp").rollout().latest();
                    }
                  }
                }
              }
            }
          }
        }
    type: JenkinsPipeline