---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tinyapp
spec:
  host: "*"
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels:
      app: tinyapp
      version: v1
  - name: v2
    labels:
      app: tinyapp
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tinyapp
spec:
  hosts:
  - "*"
  gateways:
  - tinyapp-gateway
  http:
  - match:
    - uri:
        prefix: /tinyapp
    rewrite:
      uri: /
    route:
    - destination:
        host: tinyapp
        subset: v1
      weight: 100
    - destination:
        host: tinyapp
        subset: v2
      weight: 0